'From Cuis 5.0 of 7 November 2016 [latest update: #3795] on 3 July 2019 at 10:06:58 pm'!
'Description '!
!provides: 'VAST export' 1 1!
SystemOrganization addCategory: #'VAST export'!


!classDefinition: #VASTExportCodePackage category: #'VAST export'!
CodePackage subclass: #VASTExportCodePackage
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'VAST export'!
!classDefinition: 'VASTExportCodePackage class' category: #'VAST export'!
VASTExportCodePackage class
	instanceVariableNames: ''!


!VASTExportCodePackage class methodsFor: 'instance creation' stamp: 'gera 7/3/2019 21:41:03'!
from: aCodePackage
	^self new copyFrom: aCodePackage! !
VASTExportCodePackage prePackageInstall!
!classDefinition: #VASTExportCodePackage category: #'VAST export'!
CodePackage subclass: #VASTExportCodePackage
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'VAST export'!
!classDefinition: 'VASTExportCodePackage class' category: #'VAST export'!
VASTExportCodePackage class
	instanceVariableNames: ''!


!VASTExportCodePackage class methodsFor: 'instance creation' stamp: 'gera 7/3/2019 21:41:03'!
from: aCodePackage
	^self new copyFrom: aCodePackage! !
VASTExportCodePackage postPackageInstall!
